@startuml Sequence Diagram stopBag
title Sequence Diagram stopBag

participant rosbag2_transport::Recorder as rec
participant BlackBox as sys

-> sys : stopBag()
Activate rec
rec -> rec : stop()
rec -> rec : reset()
deactivate rec

@enduml