/blackbox_provider:
  ros__parameters:
    topic_list:
      - /provider_depth/depth
      - /provider_imu/imu_info
      - /provider_dvl/dvl_velocity
      - /zed/zed_node/imu/data
      - /proc_control/controller_info
      - /provider_power/battery_voltages
      - /provider_power/battery_currents
      - /provider_power/battery_temperatures
      - /provider_power/motor_voltages
      - /provider_power/motor_currents
      - /provider_power/motor_temperatures